### ISSUE TITLE
use login shell rather than reading ~/.profile

### ISSUE THREAD

**Issue by skewballfox** [pop-os/cosmic-session#23]
The initialization behavior, and whether profile is read, varies from shell to shell, often .profile is not read at all. 
if I remember correctly:
- bash uses `.profile` if `.bash_profile` doesn't exist in home or `$XDG_CONFIG_HOME/bash`
- fish just reads `$XDG_CONFIG_HOME/fish/config.fish` and has a special flag for running the login shell
- zsh uses `.z_profile`, I'm not sure if it checks for .profile if .z_profile isn't present.

shells have a -l flag that runs them as a login shell, which does thing such as read the appropriate profile and I think set a few environment variables. I'd recommend using that

**Comment by jokeyrhyme** [comment]
`gnome-session` starts the user's preferred SHELL and uses that to call itself: https://gitlab.gnome.org/GNOME/gnome-session/-/blob/998ed1d8ee2ff5396583c284230648625b4103e5/gnome-session/gnome-session.in#L10
