### ISSUE TITLE
cosmic applications started by cosmic-session being force killed causes cosmic-comp to freeze

### ISSUE THREAD

**Issue by Quackdoc** [pop-os/cosmic-session#56]
When you start cosmic via cosmic-session is starts many applications applets etc. when one of them is force killed via `pkill` it will cause cosmic-comp to lock up, i've noticed this with cosmic-bg and cosmic-panel. They should be able to stop elegantly without effecting anything else.

EDIT: for context all my images are JXL so I have a script that uses swaybg to set background, so it doesn't make a lot of sense to have cosmic-bg running in the background too. as for cosmic panel, sometimes it's performance plummets with the cursor hovering over it and killing it to restart it fixed perf. (another option is to re-arrange the applets, this will cause it to restart)

**Comment by Drakulix** [comment]
A fix for this is already bubbling up through the stack and was just merged into wayland-backend: https://github.com/Smithay/wayland-rs/pull/741

This still needs to be updated in smithay and then in cosmic-comp until it is finally fixed.

**Comment by Drakulix** [comment]
Fixed by https://github.com/pop-os/cosmic-comp/commit/b3b9eadfcad7dd7c0696f46199d99d433ec13125
