### ISSUE TITLE
Import PGP key issue

### ISSUE THREAD

**Issue by Sophistiqq** [pop-os/cosmic-session#86]
Hi, noob here and I tried to install cosmic desktop in arch setup

error: key "3D4C5008BB5C8D29" could not be looked up remotely
error: required key missing from keyring
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.

Is there something I need to do first?

tried using yay and pacman

**Comment by OpenBagTwo** [comment]
Looks like your keyring is out of date. On Arch, you really need to be making sure to run full system upgrades regularly via `yay -Syu` (or `pacman`). To fix this issue, the following four commands have always worked for me in the past:

```bash
pacman-key --init
pacman-key --populate
pacman-key --refresh-keys
pacman -Sy archlinux-keyring
```

* [Background information](https://wiki.archlinux.org/title/Pacman/Package_signing)
* [Discussion](https://bbs.archlinux.org/viewtopic.php?id=187746)

**Comment by Sophistiqq** [comment]
Thanks, that worked flawlessly.
