### ISSUE TITLE
some apps failing to open dconf profile

### ISSUE THREAD

**Issue by michaelBelsanti** [pop-os/cosmic-session#98]
Some apps are failing to open the cosmic dconf profile added in #90. Most of the apps I've found that use dconf work fine, but so far Lutris and Bottles output a warning and fail to load settings: 

`unable to open named profile (cosmic): using the null configuration.`

**Comment by Xionical1** [comment]
Looks like there are some smart people on the arch linux forums that have figured out a temporary fix to this. Not sure if this is the correct way to solve this issue. Let me know how you installed cosmic, maybe its just a problem with the build script on arch?

https://bbs.archlinux.org/viewtopic.php?id=301557
Basically just create the dir/file '/etc/dconf/profile/cosmic' and put the line:
```
user-db:user
```
in the file, save, and relog. Fixed it right away for me.

I have installed it on arch using archinstall, then installing cosmic-session through paru on the extras repo.

**Comment by michaelBelsanti** [comment]
I am running this on NixOS. I already updated the packaging to place the dconf file in the right spot, and that fixed most apps, but not all of them. Can you test specifically lutris and bottles on your system? It could be an issue specific to them on NixOS.

**Comment by yochananmarqos** [comment]
> the line:

user-db:user

Huh? The [included dconf profile](https://github.com/pop-os/cosmic-session/blob/master/data/dconf/profile/cosmic) already does this which is included in both the Arch extra package and AUR VCS package.

**Comment by Xionical1** [comment]
> The [included dconf profile](https://github.com/pop-os/cosmic-session/blob/master/data/dconf/profile/cosmic)

Huh, I knew the file most likely existed somewhere. Re-reading the [90](https://github.com/pop-os/cosmic-session/pull/90) it looks like it might be stored under a seperate directory. I don't know why but the file was not in /etc/dconf/profile. Infact, that directory didn't exist.

**Comment by yochananmarqos** [comment]
> it might be stored under a ~~seperate~~ separate directory

Yes, it's installed to `/usr/share/dconf/profile/` just like GDM's Dconf profile is.

**Comment by michaelBelsanti** [comment]
The problem on arch was that when the profile was added, the default location was for debian based distros. Arch and many other distro's use `/etc/dconf/profile`, not `/usr/share/dconf/profile`. A variable was added to the justfile to modify this and there was a period where the Arch script had not yet been updated, leading to this issue happening on all dconf apps.

I have already fixed this varible in the cosmic packaging for NixOS, but the issue is still occuring with a select few apps that use dconf.

**Comment by yochananmarqos** [comment]
@michaelBelsanti I don't know what you're referring to. The profile was [just added](https://gitlab.archlinux.org/archlinux/packaging/packages/cosmic-session/-/commits/main) with `cosmic-session` 1.0.0.alpha.4-1. I imagine you're referring to before that?

Either way, normally, `/usr/share/` is for upstream defaults while `/etc/` is for overrides. 

As far as NiXOS packaging, it [looks like ](https://github.com/NixOS/nixpkgs/commits/nixos-unstable/pkgs/by-name/co/cosmic-session/package.nix)it's quite behind.

**Comment by michaelBelsanti** [comment]
I just explaning for the fix they mentioned, which fixed the issue on Arch for the day between the [package being updated](https://gitlab.archlinux.org/archlinux/packaging/packages/cosmic-session/-/commit/deeea3d433f1829c9ad126ddbef134749672e362) and [the profile being made to install correctly](https://gitlab.archlinux.org/archlinux/packaging/packages/cosmic-session/-/blob/dcf0746c9bed93f1352010ffa3a5fe0a56c51da3/PKGBUILD), although I misremembered it, so my comment about that path depending on the distro was incorrect. Thank you for explaining it. 

That issue isn't really related to what is happening here. I do use the repo you linked, which does install the dconf profile, but some software is still having issues opening the it. For example, Easyeffects and Boxes have no issue with the cosmic profile, but others, like Lutris and Bottles fail to open it with the error I mentioned before.

If anybody could confirm whether or not these apps have this issue on a non-NixOS system, I would appreciate it. It could be something related to how they're packaged on NixOS.

**Comment by michaelBelsanti** [comment]
I've confirmed this issue is being caused by how these apps are packaged on NixOS.
